### ISSUE TITLE
tackons may not be working

### ISSUE THREAD

**Issue by mk270** [mk270/whitakers-words#46] opened 2015-08-07 22:54 UTC
"videsne" is decomposed correctly by the copy of WORDS at Notre Dame, but not by our version

The token "TACKON" should appear in the gloss, but it doesn't seem to.

Expected: output analogous to http://www.archives.nd.edu/cgi-bin/wordz.pl?keyword=videsne

```
ne                   TACKON                             
-ne = is it not that (enclitic); or ...(introduces a question or alternative);
vid.es               V      2 1 PRES ACTIVE  IND 2 S    
video, videre, vidi, visus  V   [XXXAX]  
see, look at; consider; (PASS) seem, seem good, appear, be seen;
```

Observed, e.g. via http://latin.ucant.org/cgi-bin/translate.cgi?query=videsne :

```
videsne                          ========   UNKNOWN    
```

This may be a config error, an error we've introduced, or a bug introduced by Whitaker after Notre Dame took their copy (or even worse, a bug silently fixed by ND)

**Comment by mscuthbert** [comment] 2015-08-11 14:46
It's not a bug that we've introduced because the bug is also in my version compiled from the pre-GitHub 1.97 source.  So it's either a config error, a bug introduced by Whitaker after ND, or a bug silently fixed by ND. :-(

**Comment by ids1024** [comment] 2015-09-12 16:17
Have you made any attempt to contact Notre Dame? http://www.archives.nd.edu/cgi-bin/words.exe lists the name (and email) of Wm. Kevin Cawley, who seems to also have recently uploaded Whitaker's words on Sourceforge: http://sourceforge.net/projects/wwwords/.

**Comment by mk270** [comment] 2015-09-14 15:57
I was going to avoid taking ND's time until we'd got something they could use that was better than what they had.

I am in hospital at the moment so can't do much.

Hopefully the ND fork on SF isn't too far diverged from Whitaker's last release. I'll check it out when I'm discharged

**Comment by mscuthbert** [comment] 2015-09-14 15:59
get better soon!

**Comment by ids1024** [comment] 2015-09-20 21:39
Look at this: http://latin.ucant.org/cgi-bin/translate.cgi?query=quoque

It recognizes a TACKON there.

**Comment by ids1024** [comment] 2016-01-30 18:21
> This may be a config error, an error we've introduced, or a bug introduced by Whitaker after Notre Dame took their copy (or even worse, a bug silently fixed by ND)

Are copies of older versions of Whitaker's Words available somewhere?

**Closed as completed** 2016-02-21 18:29 UTC
Labels: bug
