### ISSUE TITLE
Attempting translation returns invalid pointer error

### ISSUE THREAD

**Issue by Jbithell** [mk270/whitakers-words#66] opened 2016-03-24 10:42 UTC
Running: `bin/words` returns: 

```
INFLECTION_ARRAY being loaded   --    1785 entries    --  Loaded correctly
GENERAL Dictionary loading      --   62085 stems      --  Loaded correctly
UNIQUES file loading            --      74 entries    --  Loaded correctly
ADDONS loading 18+11 TACKONS 6+129 PREFIXES 179 SUFFIXES   --  Loaded correctly
Copyright (c) 1993-2006 - Free for any use - Version 1.97FC
For updates and latest version check http://www.erols.com/whitaker/words.htm
Comments? William Whitaker, Box 51225  Midland  TX  79710  USA - whitaker@erols.com

Input a word or line of Latin and ENTER to get the forms and meanings
    Or Input @ and the name of a file containing words or lines
    Or Input # to change parameters and mode of the program
    Or Input ? to get help wherever available on individual parameters
Two empty lines (just a RETURN/ENTER) from the keyboard exits the program
English-to-Latin available
~E changes to English-to-Latin, ~L changes back     [tilde E]

=>Test
*** Error in `bin/words': free(): invalid pointer: 0x00007ff538ed76a0 ***
Exception in PARSE_LINE processing Test

=>

```

**Comment by Jbithell** [comment] 2016-03-24 10:45
Some system specs:

```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E5-2630L v2 @ 2.40GHz
stepping        : 4
microcode       : 0x1
cpu MHz         : 2399.998
cache size      : 15360 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov                                                                                         pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc                                                                                         arch_perfmon rep_good nopl eagerfpu pni pclmulqdq vmx ssse3 cx16 pcid sse4_1 ss                                                                                        e4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_                                                                                        lm arat xsaveopt vnmi ept fsgsbase tsc_adjust smep erms
bogomips        : 4799.99
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
```

_(It's a VM)_

**Comment by mk270** [comment] 2016-03-24 19:52
Thank you - this is very likely to be a duplicate of #65 - but with a more practical reproduction step! What version of the compiler are you using?

**Comment by Jbithell** [comment] 2016-03-27 18:35
Calling `apt-show-versions gnat`
returns `gnat:amd64/trusty 4.6ubuntu4 uptodate`

**Comment by mk270** [comment] 2016-03-28 23:34
I'm guessing this is on DigitalOcean?

**Comment by Jbithell** [comment] 2016-03-29 09:30
It is yes

**Comment by mk270** [comment] 2016-03-29 13:23
Can you try it with version 4.9 of the compiler/runtime?

**Comment by Jbithell** [comment] 2016-03-29 13:41
![image](https://cloud.githubusercontent.com/assets/8408967/14109825/d05dc078-f5bb-11e5-9cff-96b563c178e4.png)

I'm currently running trusty, so I'm going to upgrade and then try and run the package.
http://packages.ubuntu.com/vivid/gnat

**Comment by Jbithell** [comment] 2016-03-29 15:59
![image](https://cloud.githubusercontent.com/assets/8408967/14114648/99cc0042-f5cf-11e5-9ff5-07a8dc460ef3.png)

Buying a new VPS with a newer OS solved the problem!

**Comment by Jbithell** [comment] 2016-03-29 16:00
**Solution:** Run `sudo apt-get install gnat-4.9`

Thanks to @mk270

**Comment by mk270** [comment] 2016-03-29 19:51
we need to document what options don't work, compiler/runtime-wise. Luckily, most users will get pre-compiled binaries, once they exist, so this is just a matter of saving developer-time / time of people trying it out in source code form.

**Closed as completed** 2016-03-29 19:52 UTC
